server:
  applicationConnectors:
  - type: http
    port: 8040
  adminConnectors:
  - type: http
    port: 8041

jerseyClient:
  timeout: 10s
  connectionTimeout: 10s

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG