defaultCategoryId: 1

server:
  applicationConnectors:
  - type: http 
    port: 8050
  adminConnectors:
  - type: http
    port: 8051

jerseyClient:
  timeout: 10s
  connectionTimeout: 10s

logging:
  level: INFO
  loggers:
    patternexperiment: DEBUG