openapi: 3.0.1
paths:
  /new-products/{id}:
    get:
      operationId: getNewProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  /product-mails/{id}:
    get:
      operationId: getProductMailById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewProductMailRequest"
  /marketing-mails/{id}:
    get:
      operationId: getMarketingMailById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketingMailRequest"
  /product-mails:
    get:
      operationId: getProductMails
      parameters:
        - name: limit
          in: query
          schema:
            $ref: "#/components/schemas/IntParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NewProductMailRequest"
    post:
      operationId: sendProductMail
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/NewProductMailRequest"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /new-products:
    get:
      operationId: getNewProducts
      parameters:
        - name: limit
          in: query
          schema:
            $ref: "#/components/schemas/IntParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      operationId: addNewProduct
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Product"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /marketing-mails:
    get:
      operationId: getMarketingMails
      parameters:
        - name: limit
          in: query
          schema:
            $ref: "#/components/schemas/IntParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MarketingMailRequest"
    post:
      operationId: sendMarketingMail
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/MarketingMailRequest"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
components:
  schemas:
    Order:
      required:
        - items
      type: object
      properties:
        id:
          type: integer
          format: int64
        created:
          type: string
          format: date-time
        status:
          type: string
        customerId:
          minimum: 1
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
    BaseResponse:
      required:
        - message
        - status
        - statusCode
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: integer
          format: int32
        message:
          type: string
    IntParam:
      type: object
    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        amount:
          type: integer
          format: int32
    LongParam:
      type: object
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        categoryId:
          minimum: 1
          type: integer
          format: int64
        price:
          minimum: 0.01
          exclusiveMinimum: false
          type: number
          format: double
    NewProductMailRequest:
      required:
        - product
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        product:
          $ref: "#/components/schemas/Product"
    MarketingMailRequest:
      required:
        - order
      type: object
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
        order:
          $ref: "#/components/schemas/Order"
