openapi: 3.0.1
paths:
  /order-process:
    post:
      operationId: createOrderProcess
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
components:
  schemas:
    Order:
      required:
        - items
      type: object
      properties:
        id:
          type: integer
          format: int64
        created:
          type: string
          format: date-time
        status:
          type: string
        customerId:
          minimum: 1
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"
    BaseResponse:
      required:
        - message
        - status
        - statusCode
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: integer
          format: int32
        message:
          type: string
    OrderItem:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        amount:
          type: integer
          format: int32
