openapi: 3.0.1
paths:
  /categories/{id}:
    get:
      operationId: getCategoryById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductCategory"
    put:
      operationId: updateCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/ProductCategory"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
    delete:
      operationId: deleteCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /categories:
    get:
      operationId: getCategories
      parameters:
        - name: limit
          in: query
          schema:
            $ref: "#/components/schemas/IntParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductCategory"
    post:
      operationId: createCategory
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/ProductCategory"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
components:
  schemas:
    BaseResponse:
      required:
        - message
        - status
        - statusCode
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: integer
          format: int32
        message:
          type: string
    IntParam:
      type: object
    ProductCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        parentCategoryId:
          minimum: 0
          type: integer
          format: int64
        tags:
          type: array
          items:
            type: string
    LongParam:
      type: object
