openapi: 3.0.1
paths:
  /customers/{customerId}/credit-rating-check:
    get:
      operationId: updateAndCheckCreditRating
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreditRatingCheckResponse"
  /customers:
    get:
      operationId: getCustomers
      parameters:
        - name: limit
          in: query
          schema:
            $ref: "#/components/schemas/IntParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"
    post:
      operationId: createCustomer
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Customer"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
  /customers/{customerId}:
    get:
      operationId: getCustomerById
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    put:
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      requestBody:
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Customer"
        required: true
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
    delete:
      operationId: deleteCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/LongParam"
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
components:
  schemas:
    CreditRatingCheckResponse:
      type: object
      properties:
        customerId:
          minimum: 1
          type: integer
          format: int64
        rating:
          maximum: 6
          minimum: 1
          type: integer
          format: int32
    BaseResponse:
      required:
        - message
        - status
        - statusCode
      type: object
      properties:
        status:
          type: string
        statusCode:
          type: integer
          format: int32
        message:
          type: string
    IntParam:
      type: object
    Customer:
      required:
        - creditRating
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        creditRating:
          maximum: 6
          minimum: 1
          type: integer
          format: int32
    LongParam:
      type: object
